### ISSUE TITLE
detect existing file directroy

### ISSUE THREAD

**Issue by arpit1997** [ITCoders/SyncIt#1]
```
arpit@arpit-HP-Pavilion-g4-Notebook-PC:~/DevOS$ python3 sync.py 
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&client_id=876681967504-
r3ru6cf05s432d653gige0k6flggt61d.apps.googleusercontent.com&redirect_uri=http%3A%2F%
2Flocalhost%3A8080%2F&response_type=code&access_type=offline

Created new window in existing browser session.
Authentication successful.
Complete Authentication Flow First
Logged in as201451044
Your Existing File Directory
gui.pyc
Enter Name of Folder You Want to Use
Enter '/' to use current folder
Enter ':' to create New Folder and use that
:
Enter Name of Folder You Want to Create
hello
Traceback (most recent call last):
  File "sync.py", line 153, in <module>
    id_of_working_drive_folder=sync_object.folder_browser(structure,root_id)
  File "sync.py", line 130, in folder_browser
    os.makedirs(HOME_DIRECTORY+ROOT_FOLDER_NAME+os.path.sep+USERNAME)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/arpit/SyncIt/201451044'
```

**Comment by NavneetNandan** [comment]
Resolved in latest commit. Kindly recheck and close the issue if resolved successfully.
